### ISSUE TITLE
[Issue] Weekly Reset

### ISSUE THREAD

**Issue by antocs** [Valorayne/BlishHudTodos#21]
I installed the module after today's weekly reset and it still use that as reset, not next week's.
(I close discord when I play, sorry for the quality)
![16575726527138916717788877120020](https://user-images.githubusercontent.com/22413659/178355879-2feb1652-2dab-47a6-8bd9-dae71c37ad67.jpg)

**Comment by Valorayne** [comment]
Thank you very much for the report! 😊 Could you confirm it's fixed in this build here?
[Todo List.zip](https://github.com/Valorayne/BlishHudTodos/files/9091155/Todo.List.zip)

**Comment by antocs** [comment]
Fixed, but the bug of the scrolling slider (mentioned in #22) happens on this build too, it's probably something that was already present in the first released build.
