### ISSUE TITLE
Scroll on edit

### ISSUE THREAD

**Issue by antocs** [Valorayne/BlishHudTodos#22]
When you press on the edit button, it scrolls to the top.
It seems to happen only once on every daily you have.
It happens again disabling and enabling the module, so it should happen restarting Blish too.

**Comment by antocs** [comment]
It seems to be fixed, but now if you try to scroll with the slider on the left, it also triggers the window resize (hovering the slider also enlighten the bottom right corner icon for resize).

**Comment by Valorayne** [comment]
Thank you for the confirmation, but I'm not sure I understood the problem you describe 🤔 
First, I don't know what slider you're talking about. There should be a scrollbar on the right side, but not on the left side.
Also the size of the resize handler is something I don't have control over - if it interferes with your management of the list, I'd recommend the new "Fixate Window" option which prevents resizing and moving when activated :)

**Comment by antocs** [comment]
Yea sorry I was half asleep and didnt got anything right lol.
Yes, the scrollbar on the right, at some point you click on it but you are also clicking on the resize button.
Ill try to check that tho.

**Comment by Valorayne** [comment]
Thank you! 😊 
You can find a build with the bespoken option here: https://github.com/Valorayne/BlishHudTodos/discussions/17
