### ISSUE TITLE
Unable to check items after reset

### ISSUE THREAD

**Issue by ArthurZCB** [Valorayne/BlishHudTodos#24]
Unsure about the cause of this bug, but after reset I can't check off **Reappeared** items even after restarting BlishHUD. I was able to check off the "weekly strike" item that I didn't complete before reset.

**Comment by Valorayne** [comment]
Should be fixed in the latest version: https://github.com/Valorayne/BlishHudTodos/releases/tag/v0.2.0-preview 
Thanks for the report! 😊

**Comment by ArthurZCB** [comment]
I have downloaded the v1.0.1 releases and the issue seemed to be solved while raising a similar issue.
With "Hide already done task" toggled the daily task will go away, but not truly checked off. Untoggle that option will show the task with no check mark, closing and reopening the window also causes them to show up even with "Hide already done task" toggle on.
This seems to only occur when task is set to daily reset. Currently can be by passed by using local time and set it to server reset time.

**Comment by Valorayne** [comment]
What a fascinating and extensive error report! 🤔 thank you very much!
Will investigate :)

**Comment by Valorayne** [comment]
@ArthurZCB is this fixed in version 1.0.2? :)

**Comment by ArthurZCB** [comment]
Yup, everything is working perfectly fine after the update. Thank you for your work, this is a great module!
