### ISSUE TITLE
Todos Window no longer showing up

### ISSUE THREAD

**Issue by blackjackkent** [Valorayne/BlishHudTodos#40]
Hello! Really loving this module; thanks so much for making it!

I'm running into a problem, however. My todo list is very abruptly, as of last night, no longer showing up, either when I click on the todo icon or use the hotkey. It was working fine earlier yesterday so I'm not sure what happened. I tried looking through the BlishHud logs and didn't see any obvious error messages but I can provide them if necessary. My other thought was that maybe the window has somehow relocated itself offscreen?

Do you have any thoughts on how I can figure out what is wrong or how to fix it? Happy to provide any other information if needed.

Thanks much!

**Comment by Valorayne** [comment]
Thank you very much 😊 

Could you try resetting the module settings? I tried it and your todos should remain as long as you don't also empty the Todos Directory :)

![image](https://user-images.githubusercontent.com/18592310/185976446-42b4f1b9-3ed9-4730-aeed-cee929a936f5.png)

**Comment by blackjackkent** [comment]
!!! That fixed it, yay! :D

Thanks so much for the quick reply! No idea what happened but it's back now. Very happy to see it; I've quickly become dependent on this for my day to day. ;) (If you have a Ko-fi or tip jar or anything I'd happily donate a bit.)

**Comment by Valorayne** [comment]
Naww glad it worked 😊 the position of the window is stored in the module settings, so if they are incredibly weird (happens to me sometimes when moving GW2 as a window from one monitor to another), you can reset them that way. Just watch out to also re-apply all other setting changes you've made, as they're going to be reverted as well. Maybe I should add a "reset window" button at some point 🤔 

Thank you very much for your willingness to donate, but I personally don't need the money as much as others might. Instead it's an honour for me that I was able to create something that is of value to you 😊 If you want to do me a favour, then just stay as positive as you are and share that love with the rest of this awesome community 😊 And if you really want to donate, then maybe donate to "Freesnöw", the creator of BlishHUD, as he made my work possible in the first place 😊 have a great day! ❤️
