### ISSUE TITLE
Easier way to move entries ?

### ISSUE THREAD

**Issue by Arkane-x6** [Valorayne/BlishHudTodos#41]
I like to organize my list (for prioritizing mostly). Move down/up buttons are nice, but tedious when there are many entries.
So it could be really nice to have a quicker/easier way to do that :)
*eg.* 
- Drag & drop
- Have an order-number to edit for each entries
*(move entries # 25 to # 3)*
- Have the buttons *move down/up* not in each lines but in a common area  ?  
*(allows to spam click to move an entries without to re-aim the button each time)*

**Comment by Valorayne** [comment]
Has been resolved in version 1.1.2 😊 Thank you very much for the input!
